apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: wordpress
  labels:
    app: wordpress
    tier: wp
spec:
  serviceName: wordpress
  replicas: 5
  template:
    metadata:
      labels:
        app: wordpress
        tier: wp
    spec:
      containers:
      - name: wordpress
        image: wordpress
        ports:
        - name: wordpress 
          containerPort: 80
        env:
          - name: WORDPRESS_DB_HOST
            value: mysql
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: password
